### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by marinkobabic** [lanwin/log4net.NLogAppender#2]
Thank you very much for the nuget package :-)

Can you please update the package using the actual logger versions and provide a strong named package. The strong name is actually the only reason I can't use your great implementation.

**Comment by lanwin** [comment]
Sorry for my late reply, I published an updated version recently.

I dont want to put any of my limited time into creating an strong name version cause I dont need that. But I would love to apply a pullrequest when available.

**Comment by marinkobabic** [comment]
We don't use strong name anymore. Thanks anyway.

**Comment by lanwin** [comment]
Nice to hear :+1:
