### ISSUE TITLE
NLog 3

### ISSUE THREAD

**Issue by chrisdrobison** [lanwin/log4net.NLogAppender#3]
The Nuget package no longer works against NLog 3.

**Comment by lanwin** [comment]
Thanks for your report. What error do you get?

**Comment by chrisdrobison** [comment]
Nevermind, it looks like it still works with the assembly bindings in place and after a clean rebuild. But, that being said, it might be good to get a package out there built against the new major version.

**Comment by lanwin** [comment]
Up updated and published a new version with has newer bindings. But as you said, when the assembly bindings are correct, it should work without any problem.
